### ISSUE TITLE
Names of attributes within query string

### ISSUE THREAD

**Issue by siim-** [metaverse/truss#126]
When using the exposed HTTP API of a Truss generated web service the query parameter names are required to be in PascalCase. This makes sense when you think about the underlying Go data structure, but it would feel a bit more HTTPish (this is of course debatable) and consistent if instead the snake cased names used for the JSON attributes were accepted.

**Comment by hasLeland** [comment]
@siim- @hasAdamr @hasIan @zaquestion 
I think that this is quite possible to do. What follows is my attempt to write
up a sort of "proposal" for what this entails. Feel free to heckle the heck out
of this, it's meant to be my thoughts on what I understand the objective to be,
how things work currently, and how I think we should change them to end up
where we want them to be.

-----

The proposed change would be to switch the expected format for the names of
variables in the query from the current style, which is to use "PascalCase" or
"CamelCase" names, to instead use the names specified in the source `.proto`
messages, which *may* be in "snake_case".

### Background on what truss has to work with

Currently, the name for a field used in the query is the name of the field in
the `go` structures generated from the `.proto` file. Since fields on a `go`
struct must begin with uppercase (to be publicly accessible), and since
"PascalCase" is the naming convention of fields in `go`, the `protoc-gen-go`
tool (written and maintained by Google) will convert the names of message
fields from "snake_case" into "PascalCase".

In addition, the generated `go` structs contain struct tags that indicate that
when marshalling to JSON, the field names to be used in the JSON messages are
not the names of the `go` structs, but instead the original names of the fields
on the Protocol Buffer message fields.

As a result, the mapping from names of fields on Protocol Buffer messages to
the names of fields on a Go struct must look like this:

```
===== Figure 1. =====

// Protocol buffer message
message OddFieldNames {
    int64 snake_case = 1;
    int64 camelCase = 2;
    int64 __why__so__many__underscores = 3;
}

// Generated Go struct
type OddFieldNames struct {
//   "GoName"                                                                                    "JSONName"
//  ┌───────┐                                                                                    ┌────────┐
    SnakeCase                int64 `protobuf:"varint,1,opt,name=snake_case,json=snakeCase" json:"snake_case,omitempty"`
    CamelCase                int64 `protobuf:"varint,2,opt,name=camelCase" json:"camelCase,omitempty"`
    XWhy_So_Many_Underscores int64 `protobuf:"varint,3,opt,name=__why__so__many__underscores,json=WhySoManyUnderscores" json:"__why__so__many__underscores,omitempty"`
}
```

### Current implementation

`truss` operates by parsing those generated `go` structures, which happens in the `svcdef` package.

Unfortunately, right now `svcdef` does not parse the struct tags of fields at
all, so `truss` currently doesn't even know what the original/JSON field names
are. This might sound strange, since a generated service will correctly
populate the body of a response with the JSON names. However, those names
aren't explicitly set by code generated by `truss`; `truss` generates code
which passes body encoding off to `json.Marshal` and `json.Marshal` uses
runtime reflection to set those names based on the struct tags.

In order for the generated HTTP transport code to even know what the JSONName
of a variable should be, `svcdef` will need to be modified to start parsing the
struct tags for the fields.

### Changes to make

Based on what I've written above, the steps to carry this out would be as follows:

1. Expand `svcdef` to parse the struct tags of fields
2. Within `gengokit/httptransport`, the JSONName of the field must be extracted from the struct tag
3. The JSONName must then be incorporated into the generated HTTP transport code for the marshalling and unmarshalling of query parameters
