### ISSUE TITLE
Proto file containing `oneof` field causes panic

### ISSUE THREAD

**Issue by pauln** [metaverse/truss#225]
Attempting to run a proto file which contains a `oneof` field through Truss results in a panic, as the generated code for it in the `.pb.go` file includes an interface which gets picked up as though it was a service in `svcdev.New` - but can't be processed by `svcdef.NewServiceMethod`.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x642ddc]

goroutine 1 [running]:
github.com/TuneLab/truss/svcdef.NewServiceMethod(0xc420127ac0, 0xc42016e240, 0x722d6d, 0x6, 0x0)
	/home/paul/go/src/github.com/TuneLab/truss/svcdef/svcdef.go:361 +0xbc
github.com/TuneLab/truss/svcdef.NewService(0xc420130240, 0xc42016e240, 0x8, 0x8, 0x9)
	/home/paul/go/src/github.com/TuneLab/truss/svcdef/svcdef.go:329 +0x14e
github.com/TuneLab/truss/svcdef.New(0xc4200ec060, 0xc4200ec090, 0x1, 0xc4200ec090, 0x0)
	/home/paul/go/src/github.com/TuneLab/truss/svcdef/svcdef.go:236 +0x8be
github.com/TuneLab/truss/truss/parsesvcname.FromPaths(0xc420016dd0, 0x1, 0x1, 0xc420016df0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/paul/go/src/github.com/TuneLab/truss/truss/parsesvcname/parsesvcname.go:61 +0x52d
main.parseInput(0x40f904, 0x20, 0x6dd220)
	/home/paul/go/src/github.com/TuneLab/truss/cmd/truss/main.go:146 +0x20a
main.main()
	/home/paul/go/src/github.com/TuneLab/truss/cmd/truss/main.go:103 +0xc6
```

This initial hurdle can be overcome by changing the `*ast.InterfaceType` case in `svcdev.New` from:
```go
if strings.HasSuffix("Client", t.Name.Name) {
	break
}
```
(which, incidentally, has the parameters around the wrong way anyway - so it doesn't skip "Client" interfaces, though the comment above this `if` says that it does) to:
```go
if !strings.HasSuffix(t.Name.Name, "Server") {
	break
}
```
However, the generated encoders/decoders don't leverage the generated `_OneofMarshaler` and `_OneofUnmarshaler` (in the `.pb.go`), so the field remains unset.

**Comment by adamryman** [comment]
Hi @pauln,

`oneof` is not currently supported by truss.

[Here is a page showing which `protobuf`/`gRPC`features are currently supported and which ones have known issues.](https://github.com/TuneLab/truss/wiki/Supported-protobuf-and-gRPC-features)

Though to discuss the problem truss is running into with the code generated by `oneof`:

The code that you showed in `svcdef`:
```
if strings.HasSuffix("Client", t.Name.Name) {
	break
}
```
that code does "skip" the `Client` interface. `break` means that it will not call `NewService` with any interface that ends in `Client`.

The panic here happens because using `oneof` in the `proto` definition creates a new `interface` type in the `.pb.go`.

If I change `_example/echo.proto` as such
```
message EchoResponse {
  string Out = 1;
  oneof pattern {
    // Used for listing and getting information about resources.
    string get = 2;

    // Used for updating a resource.
    string put = 3;

    // Used for creating a resource.
    string post = 4;

    // Used for deleting a resource.
    string delete = 5;

    // Used for updating a resource.
    string patch = 6;
  }
}
```
Then in the generated `.pb.go` this interface exists:
```
type isEchoResponse_Pattern interface {
	isEchoResponse_Pattern()
}
```

Which `svcdef` does not know how to handle and tries to access out of bound paramaters. This is because that interface does not have parameters and `svcdef` is trying to access them.

At the very least adding checks to make sure there are the expected number of function parameters (2 in and 2 out), and logging that `svcdef` ran across an unexpected interface would be an improvement for the user of truss. Rather than panicing

If you want to add support for `oneof` a proposal issue is welcome :). We will need to figure out where the generated `oneof` code fits into truss, and how it will work with both HTTP 1.1/JSON transport and gRPC transport.

**Comment by pauln** [comment]
Hi @adamryman,
I'm aware that the code I mentioned _should_ skip the `Client` interface, but it currently doesn't as the parameters to `strings.HasSuffix` are backwards (per [the docs](https://golang.org/pkg/strings/#HasSuffix), the signature is `func HasSuffix(s, suffix string) bool` but it's being called as `strings.HasSuffix("Client", t.Name.Name)`) - it's skipping any interface whose full name is a suffix of the fixed string `"Client"`, i.e. not skipping anything at all.  As part of my cursory investigation, I added some extra debug output which showed that `Client` interfaces are indeed currently being processed.

Logging that an unexpected/unsupported interface was found is definitely a good idea, though; I'll flick through a quick fix PR which stops the panic by limiting it to `Server` interfaces and logs anything which isn't either `Server` or `Client`.  I'll try to find time to dig deeper into actually adding support for `oneof` fields after that, but can't make any promises.

**Comment by adamryman** [comment]
My mistake @pauln, thanks for correcting. 

And thanks for the PR! :100: Always glad to remove panics and improve logging.

We do not have supporting `oneof` on our roadmap and do not anticipate it becoming a priority, though we would love to see it added one day.

**Comment by pauln** [comment]
As it turns out, `oneof` seems to be supported (at least to some degree; I'll dig a little deeper to confirm whether it's adequately supported soon) already by the gRPC side of things.  The main issue is unmarshalling from JSON, which seems to be resolved by using [golang/protobuf/jsonpb](http://github.com/golang/protobuf/jsonpb) rather than `encoding/json`.

Unfortunately, `jsonpb` isn't a drop-in replacement - but I've hacked it into a generated Truss project for unmarshalling from JSON, which has resulted in the `oneof` field being populated.  I'll look at marshalling back to JSON using `jsonpb` next, and then work on updating the codegen to use `jsonpb`.

**Comment by pauln** [comment]
PR #227 uses `jsonpb` where relevant, and should confer support for `oneof` in HTTP/JSON.  I'll close this issue now, as the panic is resolved.
